version: "3.7"

services:
  nzbhydra2:
    container_name: nzbhydra2
    image: cr.hotio.dev/hotio/nzbhydra2
    ports:
      - "5076:5076"
    environment:
      - PUID=1024
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/nzbhydra:/config