version: '3.3'
services:
    linuxserver:
        container_name: ombi
        environment:
            - PUID=1024
            - PGID=100
            - TZ=Europe/London
        ports:
            - '5056:3579'
        volumes:
            - '/volume1/docker/ombi:/config'
        restart: unless-stopped
        image: lscr.io/linuxserver/ombi