version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/London
      - PUID=1024
      - PGID=100
      - UMASK_SET=002
      - serverIP=192.168.10.245
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /volume1/docker/tdarr/server:/app/server
      - /volume1/docker/tdarr/configs:/app/configs
      - /volume1/docker/tdarr/logs:/app/logs
      - /volume2/Media2/other2:/other2
      - /volume2/Media2/Movie:/Movie
      - /volume2/Media2/TV:/TV
      - /volume2/Media2/Tdarrtest:/Tdarrtest
      - /volume1/docker/tdarr/transcode_cache:/temp


# node example
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=Europe/London
      - PUID=1024
      - PGID=100
      - UMASK_SET=002
      - nodeID=MainNode
      - serverIP=192.168.10.245
      - serverPort=8266
    volumes:
      - /volume1/docker/tdarr/configs:/app/configs
      - /volume1/docker/tdarr/logs:/app/logs
      - /volume2/Media2/other2:/other2
      - /volume2/Media2/Movie:/Movie
      - /volume2/Media2/TV:/TV
      - /volume2/Media2/Tdarrtest:/Tdarrtest
      - /volume1/docker/tdarr/transcode_cache:/temp
