 gaps:
    image: housewrecker/gaps:latest
    container_name: gaps
    ports:
      - 5211:8484
    expose:
      - 32400
    volumes:
      - /volume1/downloads/gaps:/usr/data
    restart: unless-stopped