version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - PIHOLE_UID=YOURUID
      - PIHOLE_GID=YOURGID
      - WEB_UID=YOURUID
      - WEB_GID=YOURGID
      - TZ=Europe/London
      - WEBPASSWORD=YOURPASSWORD
      - DNSMASQ_LISTENING=local
      - WEB_PORT=8000
      - DNSMASQ_USER=pihole
      - FTLCONF_LOCAL_IPV4=192.168.10.245
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /volume1/docker/pihole/pihole:/etc/pihole
    network_mode: host
    restart: unless-stopped