version: '3.3'
services:
    volume1:
        container_name: grafana
        ports:
            - '3010:3000'
        volumes:
            - '/volume1/docker/grafana:/var/lib/grafana'
        restart: always
        image: grafana/grafana