version: '3.3'
services:
    grafana:
        container_name: grafana
        image: grafana/grafana
        user: "1024"
        ports:
            - "3000:3000"  
        volumes:
         - /volume1/docker/grafana:/var/lib/grafana