version: '3.3'
services:
    linuxserver:
        container_name: radarr
        ports:
            - '7878:7878'
        environment:
            - PUID=1024
            - PGID=100
            - TZ=Europe/London
        volumes:
            - '/volume1/docker/radarr:/config'
            - '/volume2/Media2/Movie:/movies'
            - '/volume2/Media2/TV/TV Shows:/tv'
            - '/volume2/Media2/Downloads:/tv'

        restart: always
        image: ghcr.io/linuxserver/radarr