---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1038
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /volume1/docker/media/radarr/config:/config
      - /volume2/Media2/Films/Movies:/movies 
      - /volume1/docker/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped