version: '3.3'
services:
    homebridge:
        container_name: homebridge
        environment:
            - DSM_HOSTNAME=DS216
        volumes:
            - '/volume1/docker/homebridge:/homebridge'
        network_mode: host
        restart: always
        image: oznu/homebridge
