version: '3.3'
services:
    minio:
        restart: always
        ports:
            - '9001:9001'
        container_name: minio-container-name
        environment:
            - MINIO_ROOT_USER=username
            - MINIO_ROOT_PASSWORD=password
        volumes:
            - '/Yourname/test:/data'
        image: \